name: Python App CI/CD Pipeline with Direct Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-for-vmss:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - run: |
        pip install -r requirements.txt

    # Run tests (Placeholder for actual tests)
    - name: Run tests
      run: |
        echo "Run tests"

    # Azure Login using GitHub Secrets
    - name: Azure Login
      uses: azure/login@v2.2.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Execute the Update Script on the VM
    - name: Deploy to Azure VM
      run: |    
       az vmss extension set \
        --resource-group ${{ secrets.RESOURCE_GROUP }} \
        --vmss-name ${{ secrets.VMSS_NAME }} \
        --name CustomScript \
        --publisher Microsoft.Azure.Extensions \
        --type CustomScript \
        --type-handler-version 2.1 \
        --settings '{"commandToExecute": "/home/azureuser/Terraform-AZ-St6.5/update_app.sh"}' \
        --force-update
